version: '3.8'
services:
  frontend:
    image: badbuzzacr.azurecr.io/badbuzz-frontend:latest
    environment:
      - API_URL=http://localhost:5000/predict
      - WEBSITES_PORT=8501
    ports:
      - "8501:8501"

  api:
    image: badbuzzacr.azurecr.io/badbuzz-api:latest
    ports:
      - "5000"