services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: badbuzz_api
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      # Commande pour vérifier si l'API est prête à recevoir des requêtes.
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      # No args needed here as it uses its own requirements file
    container_name: badbuzz_frontend
    ports:
      - "8501:8501"
    depends_on: # Attend que le service 'api' soit "healthy" avant de démarrer.
      api:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - API_URL=http://api:5000/predict
