version: '3.8'
services:
  frontend:
    image: badbuzzacr.azurecr.io/badbuzz-frontend:latest
    environment:
      - API_URL=http://localhost:5000/predict
      - WEBSITES_PORT=8501
    ports:
      - "8501:8501"

  api:
    image: badbuzzacr.azurecr.io/badbuzz-api:latest
    ports:
      - "5000"
    environment:
      - LOG_LEVEL=INFO
      - WEBSITES_CONTAINER_START_TIME_LIMIT=600
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s