services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - MODEL_URL=${MODEL_URL}
        - VECTORIZER_URL=${VECTORIZER_URL}
    container_name: badbuzz_api
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      # No args needed here as it uses its own requirements file
    container_name: badbuzz_frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - API_URL=http://api:5000/predict
