name: CI/CD Pipeline for Badbuzz Detection

# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      # The URL to the pipeline artifact, set in repository secrets
      PIPELINE_URL: ${{ secrets.PIPELINE_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip" # Cache dependencies to speed up future builds

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install both production and development dependencies for the test job
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Download pipeline for testing
      run: wget -O pipeline.joblib ${PIPELINE_URL}

    - name: Lint and Format Check with Ruff
      run: |
        echo "--- Checking for style and quality issues with 'ruff check' ---"
        ruff check .
        echo "--- Checking for formatting issues with 'ruff format' ---"
        ruff format --check .

    - name: Run tests and check coverage
      run: |
        # Run tests, generate a report in the terminal, and fail the build
        # if test coverage is below 90%.
        pytest --cov=app --cov-report=html --cov-report=term-missing --cov-fail-under=50

    - name: Upload HTML coverage report
      # This step always runs, even if the previous one fails,
      # so you can review the report.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: htmlcov/

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    # This job runs only if the 'test' job succeeds
    needs: test
    # This job runs only on pushes to the main branch, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Download pipeline for Docker build
      env:
        PIPELINE_URL: ${{ secrets.PIPELINE_URL }}
      run: wget -O pipeline.joblib ${PIPELINE_URL}

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./api.Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/badbuzz-api:latest,${{ secrets.ACR_LOGIN_SERVER }}/badbuzz-api:${{ github.sha }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./frontend.Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/badbuzz-frontend:latest,${{ secrets.ACR_LOGIN_SERVER }}/badbuzz-frontend:${{ github.sha }}

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: Staging
      url: https://badbuzz-webapp-staging.azurewebsites.net
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App (Staging Slot)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'badbuzz-webapp'
          slot-name: 'staging'
          # Les images ont déjà été poussées dans le job précédent.
          # Azure App Service va automatiquement pull les images 'latest'.

  approve-for-production:
    name: Approve for Production
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    environment:
      name: Production
    steps:
      - name: Manual approval before production swap
        run: echo "After verifying the staging slot, click 'Resume workflow' to swap to production."

  swap-to-production:
    name: Swap Staging to Production
    runs-on: ubuntu-latest
    needs: approve-for-production
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Vous devrez créer ce secret

      - name: 'Swap Staging to Production'
        run: |
          az webapp deployment slot swap --name badbuzz-webapp \
            --resource-group badbuzzresourcegroup --slot staging --target-slot production